import type { Category, Product, StoreHub } from "@korre/shared";

export const categories: Category[] = [
  {
    id: "cat-trabalho-produtividade",
    name: "Trabalho e produtividade",
    slug: "trabalho-e-produtividade",
    description: "Essenciais para operar apps, atender passageiros, entregar pedidos e organizar a jornada.",
    icon: "briefcase",
    subcategories: ["Suportes para celular", "Carregadores", "Cabos", "Power banks", "Atendimento ao passageiro", "Bags de entrega", "Mochilas termicas", "Gestao da jornada"],
    sortOrder: 1,
    active: true
  },
  {
    id: "cat-tecnologia",
    name: "Tecnologia e eletronicos",
    slug: "tecnologia-e-eletronicos",
    description: "Celulares, carregamento, multimidia, cameras, sensores, diagnostico e energia conectada.",
    icon: "smartphone",
    subcategories: ["Celulares", "Carregadores", "Power banks", "Cabos reforcados", "Coolers para celular", "Impressoras portateis", "Multimidia", "Dashcams", "Cameras de re", "Sensores", "OBD2", "GPS", "Conectividade", "Rastreamento", "Equipamentos inteligentes"],
    sortOrder: 2,
    active: true
  },
  {
    id: "cat-manutencao-pecas",
    name: "Manutencao, pecas e pneus",
    slug: "manutencao-pecas-e-pneus",
    description: "Reposicao, revisao, pneus, rodas e ferramentas para manter o veiculo trabalhando.",
    icon: "wrench",
    subcategories: ["Autopecas", "Motor", "Filtros", "Freios", "Suspensao", "Direcao", "Correias", "Ignicao", "Arrefecimento", "Palhetas", "Eletrica", "Baterias", "Pneus de passeio", "Pneus SUV", "Pneus utilitarios", "Pneus de moto", "Pneus de bicicleta", "Rodas", "Calotas", "Kit reparo", "Compressor", "Selante", "Fluidos", "Ferramentas manuais", "Ferramentas eletricas", "Diagnostico", "Elevacao", "Consumiveis"],
    sortOrder: 3,
    active: true
  },
  {
    id: "cat-limpeza-estetica",
    name: "Limpeza, higiene e estetica",
    slug: "limpeza-higiene-e-estetica",
    description: "Limpeza, odores, protecao, conservacao e acabamento para manter boa apresentacao.",
    icon: "sparkles",
    subcategories: ["Limpeza interna", "Limpeza externa", "Vidros", "Estofados", "Couro", "Painel", "Rodas", "Odores", "Lavagem a seco", "Limpeza rapida", "Kits profissionais", "Protecao", "Cera", "Polimento", "Cristalizacao", "Aromatizantes", "Aspiradores", "Plastico", "Farois", "Detalhes"],
    sortOrder: 4,
    active: true
  },
  {
    id: "cat-organizacao-conforto",
    name: "Organizacao, conforto e saude",
    slug: "organizacao-conforto-e-saude",
    description: "Organizacao do veiculo, ergonomia, alimentacao e cuidados pessoais na jornada.",
    icon: "archive",
    subcategories: ["Interior", "Porta-malas", "Banco traseiro", "Console", "Documentos", "Cabos", "Ferramentas", "Pedidos", "Alimentos", "Moto", "Bicicleta", "Viagem", "Assento e postura", "Almofadas lombares", "Apoio cervical", "Temperatura", "Hidratacao", "Alimentacao", "Garrafas termicas", "Copos termicos", "Caixas termicas", "Marmitas", "Bolsas termicas", "Protecao solar", "Primeiros socorros", "Repelentes", "Alcool em gel", "Lencos"],
    sortOrder: 5,
    active: true
  },
  {
    id: "cat-seguranca",
    name: "Seguranca, clima e emergencia",
    slug: "seguranca-clima-e-emergencia",
    description: "Prevencao, chuva, visibilidade, pane, bateria, sinalizacao e primeiros cuidados.",
    icon: "shield",
    subcategories: ["Visibilidade", "Registro por camera", "Monitoramento", "Pneus", "Iluminacao", "Chuva", "Calor", "Frio", "Poeira", "Lama", "Impermeabilizacao", "Emergencia", "Bateria", "Energia", "Sinalizacao", "Primeiros cuidados", "Organizacao do kit", "Protecao para moto", "Protecao para bicicleta", "Protecao de passageiros", "Protecao do veiculo"],
    sortOrder: 6,
    active: true
  },
  {
    id: "cat-moto-delivery",
    name: "Moto, vestimentas e delivery",
    slug: "moto-vestimentas-e-delivery",
    description: "Equipamentos para motociclistas, motoboys, chuva, bags e transporte de pedidos.",
    icon: "helmet",
    subcategories: ["Capas de chuva", "Luvas", "Jaquetas", "Refletivos", "Capacetes abertos", "Capacetes fechados", "Capacetes articulados", "Off-road", "Viseiras", "Intercomunicadores", "Celular e navegacao", "Suporte para moto", "Baus", "Bagageiros", "Mochilas", "Bags termicas", "Bags impermeaveis", "Elasticos", "Redes", "Manutencao de corrente", "Conforto para moto", "Entregas"],
    sortOrder: 7,
    active: true
  },
  {
    id: "cat-bike-mobilidade",
    name: "Bike e mobilidade leve",
    slug: "bike-e-mobilidade-leve",
    description: "Bicicletas, scooters, entregas leves, seguranca, manutencao e transporte.",
    icon: "bike",
    subcategories: ["Bicicletas", "Scooter eletrica", "Iluminacao", "Seguranca", "Celular", "Bolsas e transporte", "Entregas", "Hidratacao", "Conforto para bicicleta", "Manutencao de bicicleta", "Ferramentas", "Camaras", "Correntes", "Cadeados", "Bombas"],
    sortOrder: 8,
    active: true
  },
  {
    id: "cat-acessorios-viagem-servicos",
    name: "Acessorios, viagem e servicos",
    slug: "acessorios-viagem-e-servicos",
    description: "Acessorios automotivos, viagem, passageiros, familia, documentos e protecao recorrente.",
    icon: "car",
    subcategories: ["Acessorios para carro", "Interior", "Exterior", "Tapetes", "Capas", "Peliculas", "Porta-malas", "Console", "Bancos", "Volante", "Acabamento", "Bagagem", "Viagem", "Uso rodoviario", "Navegacao", "Criancas", "Animais", "Passageiros", "Porta-copos", "Protetores de banco", "Lixeiras", "Documentos", "Controle de custos", "Quilometragem", "Planejamento", "Recibos", "Pastas", "Seguro automotivo", "Rastreadores", "Assistencia 24h", "Protecao veicular"],
    sortOrder: 9,
    active: true
  },
  {
    id: "cat-kits-korre",
    name: "Kits Loja do Korre",
    slug: "kits-loja-do-korre",
    description: "Combos prontos por profissao, clima, jornada e objetivo.",
    icon: "boxes",
    subcategories: ["Por profissao", "Por problema", "Por orcamento", "Por jornada", "Economicos", "Custo-beneficio", "Premium", "Kit chuva", "Kit noite", "Kit emergencia", "Kit delivery"],
    sortOrder: 10,
    active: true
  }
];

export const products: Product[] = [
  {
    id: "prod-suporte-celular",
    categoryId: "cat-trabalho-produtividade",
    categorySlug: "trabalho-e-produtividade",
    name: "Suporte veicular com trava reforcada",
    slug: "suporte-veicular-trava-reforcada",
    shortDescription: "Boa opcao para quem usa GPS por horas e precisa reduzir vibracao.",
    recommendationReason: "Mantem o aparelho firme e facilita visualizar rotas sem improviso no painel.",
    vehicleType: "car",
    audience: "driver",
    imageUrl: "https://images.unsplash.com/photo-1617788138017-80ad40651399?auto=format&fit=crop&w=900&q=80",
    referencePriceCents: 6990,
    currency: "BRL",
    status: "active",
    featured: true,
    tags: ["suportes para celular", "gps", "carro", "rotina"],
    bestFor: "Motoristas de app que passam o dia alternando entre mapas, chamadas e corridas.",
    avoidWhen: "O painel do veiculo nao tem area firme para ventosa ou base adesiva.",
    offer: {
      id: "offer-suporte-celular",
      provider: "mercado_livre",
      affiliateUrl: "https://www.mercadolivre.com.br/",
      active: true,
      referencePriceCents: 6990,
      updatedAt: new Date().toISOString()
    }
  },
  {
    id: "prod-cabo-reforcado",
    categoryId: "cat-tecnologia",
    categorySlug: "tecnologia-e-eletronicos",
    name: "Cabo USB-C reforcado para carga rapida",
    slug: "cabo-usb-c-reforcado-carga-rapida",
    shortDescription: "Cabo extra para deixar no carro, moto ou mochila sem depender do principal.",
    recommendationReason: "Evita parar a operacao por bateria baixa e aguenta melhor dobra e manuseio frequente.",
    vehicleType: "both",
    audience: "general",
    imageUrl: "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=900&q=80",
    referencePriceCents: 3990,
    currency: "BRL",
    status: "active",
    featured: true,
    tags: ["carregadores", "energia", "usb-c", "carga"],
    bestFor: "Quem alterna entre veiculo, power bank e tomada durante o dia.",
    avoidWhen: "Seu celular usa outro padrao de conector ou exige cabo certificado especifico.",
    offer: {
      id: "offer-cabo-reforcado",
      provider: "mercado_livre",
      affiliateUrl: "https://www.mercadolivre.com.br/",
      active: true,
      referencePriceCents: 3990,
      updatedAt: new Date().toISOString()
    }
  },
  {
    id: "prod-capa-chuva",
    categoryId: "cat-moto-delivery",
    categorySlug: "moto-vestimentas-e-delivery",
    name: "Capa de chuva para entrega",
    slug: "capa-de-chuva-para-entrega",
    shortDescription: "Camada de protecao para motoboy que nao pode parar quando o tempo vira.",
    recommendationReason: "Ajuda a manter roupa e equipamentos secos em jornadas com chuva intermitente.",
    vehicleType: "motorcycle",
    audience: "motoboy",
    imageUrl: "https://images.unsplash.com/photo-1520607162513-77705c0f0d4a?auto=format&fit=crop&w=900&q=80",
    referencePriceCents: 11990,
    currency: "BRL",
    status: "active",
    featured: false,
    tags: ["capa de chuva", "moto", "chuva", "entrega"],
    bestFor: "Entregadores que rodam mesmo em periodos de chuva e precisam secar rapido.",
    avoidWhen: "Voce precisa de EPI com certificacao especifica exigida pela empresa contratante.",
    offer: {
      id: "offer-capa-chuva",
      provider: "mercado_livre",
      affiliateUrl: "https://www.mercadolivre.com.br/",
      active: true,
      referencePriceCents: 11990,
      updatedAt: new Date().toISOString()
    }
  }
  ,
  {
    id: "prod-celular-reserva",
    categoryId: "cat-tecnologia",
    categorySlug: "tecnologia-e-eletronicos",
    name: "Celular reserva para aplicativos",
    slug: "celular-reserva-para-aplicativos",
    shortDescription: "Aparelho de apoio para quem precisa manter corridas, mapas e comunicacao sempre disponiveis.",
    recommendationReason: "Ajuda a separar uso pessoal da operacao e reduz risco de ficar sem ferramenta de trabalho.",
    vehicleType: "both",
    audience: "general",
    imageUrl: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=900&q=80",
    referencePriceCents: 79990,
    currency: "BRL",
    status: "active",
    featured: false,
    tags: ["celulares", "aplicativos", "gps"],
    bestFor: "Motoristas e entregadores que dependem do celular durante toda a jornada.",
    avoidWhen: "Voce precisa de camera premium ou alto desempenho para jogos.",
    offer: {
      id: "offer-celular-reserva",
      provider: "mercado_livre",
      affiliateUrl: "https://www.mercadolivre.com.br/",
      active: true,
      referencePriceCents: 79990,
      updatedAt: new Date().toISOString()
    }
  },
  {
    id: "prod-kit-pastilha-freio",
    categoryId: "cat-manutencao-pecas",
    categorySlug: "manutencao-pecas-e-pneus",
    name: "Kit de pastilhas de freio para revisao",
    slug: "kit-pastilhas-freio-revisao",
    shortDescription: "Item de manutencao preventiva para revisar antes de jornadas longas.",
    recommendationReason: "Freio em dia reduz risco operacional e evita parar de trabalhar por desgaste ignorado.",
    vehicleType: "motorcycle",
    audience: "motoboy",
    imageUrl: "https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=900&q=80",
    referencePriceCents: 8990,
    currency: "BRL",
    status: "active",
    featured: false,
    tags: ["pecas", "freio", "manutencao", "moto"],
    bestFor: "Motoboys que fazem revisao periodica e conhecem a compatibilidade da moto.",
    avoidWhen: "Voce nao tem certeza do modelo correto para seu veiculo.",
    offer: {
      id: "offer-kit-pastilha-freio",
      provider: "mercado_livre",
      affiliateUrl: "https://www.mercadolivre.com.br/",
      active: true,
      referencePriceCents: 8990,
      updatedAt: new Date().toISOString()
    }
  },
  {
    id: "prod-carregador-veicular-duplo",
    categoryId: "cat-trabalho-produtividade",
    categorySlug: "trabalho-e-produtividade",
    name: "Carregador veicular duplo carga rapida",
    slug: "carregador-veicular-duplo-carga-rapida",
    shortDescription: "Energia para celular do motorista e passageiro sem improvisar adaptadores.",
    recommendationReason: "Resolve o ponto mais critico da jornada: manter apps, GPS e comunicacao ligados.",
    vehicleType: "car",
    audience: "driver",
    imageUrl: "https://images.unsplash.com/photo-1603791440384-56cd371ee9a7?auto=format&fit=crop&w=900&q=80",
    referencePriceCents: 5990,
    currency: "BRL",
    status: "active",
    featured: true,
    tags: ["carregador", "celular descarregando", "atendimento ao passageiro", "energia"],
    bestFor: "Motoristas de aplicativo que precisam carregar dois aparelhos ou atender passageiro.",
    avoidWhen: "Seu veiculo ja possui USB-C nativo com potencia suficiente.",
    offer: {
      id: "offer-carregador-veicular-duplo",
      provider: "mercado_livre",
      affiliateUrl: "https://www.mercadolivre.com.br/",
      active: true,
      referencePriceCents: 5990,
      updatedAt: new Date().toISOString()
    }
  },
  {
    id: "prod-dashcam-dupla",
    categoryId: "cat-tecnologia",
    categorySlug: "tecnologia-e-eletronicos",
    name: "Dashcam dupla para registro de rota",
    slug: "dashcam-dupla-registro-rota",
    shortDescription: "Camera frontal e interna para registrar acontecimentos durante corridas e viagens.",
    recommendationReason: "Aumenta a confianca em situacoes de contestacao, incidentes e trabalho noturno.",
    vehicleType: "car",
    audience: "driver",
    imageUrl: "https://images.unsplash.com/photo-1617824040896-4b771231a33f?auto=format&fit=crop&w=900&q=80",
    referencePriceCents: 28990,
    currency: "BRL",
    status: "active",
    featured: true,
    tags: ["dashcam", "camera", "registro do transito", "seguranca"],
    bestFor: "Motoristas que transportam passageiros ou rodam em horarios de maior risco.",
    avoidWhen: "Voce nao quer lidar com instalacao, fio aparente ou cartao de memoria.",
    offer: {
      id: "offer-dashcam-dupla",
      provider: "mercado_livre",
      affiliateUrl: "https://www.mercadolivre.com.br/",
      active: true,
      referencePriceCents: 28990,
      updatedAt: new Date().toISOString()
    }
  },
  {
    id: "prod-kit-limpeza-rapida",
    categoryId: "cat-limpeza-estetica",
    categorySlug: "limpeza-higiene-e-estetica",
    name: "Kit limpeza rapida para carro de trabalho",
    slug: "kit-limpeza-rapida-carro-trabalho",
    shortDescription: "Panos, limpador interno e neutralizador para manter o carro apresentavel entre corridas.",
    recommendationReason: "Ajuda a recuperar o padrao de atendimento depois de sujeira, chuva ou passageiro descuidado.",
    vehicleType: "car",
    audience: "driver",
    imageUrl: "https://images.unsplash.com/photo-1607860108855-64acf2078ed9?auto=format&fit=crop&w=900&q=80",
    referencePriceCents: 8490,
    currency: "BRL",
    status: "active",
    featured: true,
    tags: ["limpeza", "limpeza rapida", "carro sujo", "odores"],
    bestFor: "Motoristas que precisam manter boa avaliacao sem parar muito tempo.",
    avoidWhen: "O veiculo precisa de limpeza profunda ou higienizacao profissional.",
    offer: {
      id: "offer-kit-limpeza-rapida",
      provider: "mercado_livre",
      affiliateUrl: "https://www.mercadolivre.com.br/",
      active: true,
      referencePriceCents: 8490,
      updatedAt: new Date().toISOString()
    }
  },
  {
    id: "prod-apoio-lombar-motorista",
    categoryId: "cat-organizacao-conforto",
    categorySlug: "organizacao-conforto-e-saude",
    name: "Apoio lombar para longas jornadas",
    slug: "apoio-lombar-longas-jornadas",
    shortDescription: "Almofada de suporte para reduzir desconforto em turnos prolongados.",
    recommendationReason: "Melhora postura e ajuda quem sente dor depois de muitas horas dirigindo.",
    vehicleType: "car",
    audience: "driver",
    imageUrl: "https://images.unsplash.com/photo-1550355291-bbee04a92027?auto=format&fit=crop&w=900&q=80",
    referencePriceCents: 7990,
    currency: "BRL",
    status: "active",
    featured: false,
    tags: ["conforto lombar", "desconforto", "ergonomia", "jornada longa"],
    bestFor: "Motoristas que passam horas sentados e querem uma melhoria simples de ergonomia.",
    avoidWhen: "O banco ja tem ajuste lombar eficiente ou ha dor que exige avaliacao profissional.",
    offer: {
      id: "offer-apoio-lombar-motorista",
      provider: "mercado_livre",
      affiliateUrl: "https://www.mercadolivre.com.br/",
      active: true,
      referencePriceCents: 7990,
      updatedAt: new Date().toISOString()
    }
  },
  {
    id: "prod-compressor-portatil",
    categoryId: "cat-manutencao-pecas",
    categorySlug: "manutencao-pecas-e-pneus",
    name: "Compressor portatil para pneus",
    slug: "compressor-portatil-pneus",
    shortDescription: "Calibragem e emergencia para carro, moto e bicicleta.",
    recommendationReason: "Reduz parada inesperada por pneu baixo e ajuda a economizar combustivel com calibragem correta.",
    vehicleType: "both",
    audience: "general",
    imageUrl: "https://images.unsplash.com/photo-1487754180451-c456f719a1fc?auto=format&fit=crop&w=900&q=80",
    referencePriceCents: 16990,
    currency: "BRL",
    status: "active",
    featured: true,
    tags: ["compressor", "pneu sem pressao", "calibragem", "economizar combustivel"],
    bestFor: "Quem roda muito e quer manter pressao correta sem depender sempre de posto.",
    avoidWhen: "Voce precisa inflar pneus grandes acima da capacidade do aparelho.",
    offer: {
      id: "offer-compressor-portatil",
      provider: "mercado_livre",
      affiliateUrl: "https://www.mercadolivre.com.br/",
      active: true,
      referencePriceCents: 16990,
      updatedAt: new Date().toISOString()
    }
  },
  {
    id: "prod-auxiliar-partida",
    categoryId: "cat-seguranca",
    categorySlug: "seguranca-clima-e-emergencia",
    name: "Auxiliar de partida compacto",
    slug: "auxiliar-partida-compacto",
    shortDescription: "Fonte de emergencia para bateria descarregada em rotina profissional.",
    recommendationReason: "Evita perder horas de trabalho esperando ajuda quando a bateria falha.",
    vehicleType: "car",
    audience: "driver",
    imageUrl: "https://images.unsplash.com/photo-1530046339160-ce3e530c7d2f?auto=format&fit=crop&w=900&q=80",
    referencePriceCents: 24990,
    currency: "BRL",
    status: "active",
    featured: false,
    tags: ["bateria", "bateria descarregada", "emergencia", "energia"],
    bestFor: "Motoristas que trabalham de madrugada, viajam ou rodam alta quilometragem.",
    avoidWhen: "A bateria apresenta defeito recorrente que precisa de diagnostico profissional.",
    offer: {
      id: "offer-auxiliar-partida",
      provider: "mercado_livre",
      affiliateUrl: "https://www.mercadolivre.com.br/",
      active: true,
      referencePriceCents: 24990,
      updatedAt: new Date().toISOString()
    }
  },
  {
    id: "prod-mochila-termica-delivery",
    categoryId: "cat-moto-delivery",
    categorySlug: "moto-vestimentas-e-delivery",
    name: "Mochila termica para delivery",
    slug: "mochila-termica-delivery",
    shortDescription: "Transporte de pedidos com melhor organizacao e conservacao de temperatura.",
    recommendationReason: "Ajuda a reduzir reclamacao por pedido amassado, frio ou mal acomodado.",
    vehicleType: "motorcycle",
    audience: "motoboy",
    imageUrl: "https://images.unsplash.com/photo-1526367790999-0150786686a2?auto=format&fit=crop&w=900&q=80",
    referencePriceCents: 13990,
    currency: "BRL",
    status: "active",
    featured: false,
    tags: ["delivery", "pedidos desorganizados", "mochila termica", "motoboy"],
    bestFor: "Motoboys e ciclistas entregadores que fazem rota com pedidos variados.",
    avoidWhen: "Voce precisa transportar volumes muito grandes ou caixas rigidas.",
    offer: {
      id: "offer-mochila-termica-delivery",
      provider: "mercado_livre",
      affiliateUrl: "https://www.mercadolivre.com.br/",
      active: true,
      referencePriceCents: 13990,
      updatedAt: new Date().toISOString()
    }
  },
  {
    id: "prod-kit-chuva-profissional",
    categoryId: "cat-kits-korre",
    categorySlug: "kits-loja-do-korre",
    name: "Kit chuva para rotina profissional",
    slug: "kit-chuva-rotina-profissional",
    shortDescription: "Selecao inicial para trabalhar quando o tempo vira.",
    recommendationReason: "Combina protecao pessoal, impermeabilizacao e visibilidade em um caminho de compra.",
    vehicleType: "both",
    audience: "general",
    imageUrl: "https://images.unsplash.com/photo-1493314894560-5c412a56c17c?auto=format&fit=crop&w=900&q=80",
    referencePriceCents: 19990,
    currency: "BRL",
    status: "active",
    featured: false,
    tags: ["kit chuva", "chuva", "trabalho noturno", "emergencia"],
    bestFor: "Motoristas e entregadores que querem montar uma base antes do periodo de chuvas.",
    avoidWhen: "Voce precisa de item homologado por regra especifica do contratante.",
    offer: {
      id: "offer-kit-chuva-profissional",
      provider: "mercado_livre",
      affiliateUrl: "https://www.mercadolivre.com.br/",
      active: true,
      referencePriceCents: 19990,
      updatedAt: new Date().toISOString()
    }
  }
];

export const storeHubs: StoreHub[] = [
  { id: "hub-problem-celular-descarregando", type: "problem", title: "Celular descarregando", slug: "celular-descarregando", categorySlug: "trabalho-e-produtividade", query: "carregador", items: [], priority: 1, active: true },
  { id: "hub-problem-celular-esquentando", type: "problem", title: "Celular esquentando", slug: "celular-esquentando", categorySlug: "tecnologia-e-eletronicos", query: "cooler celular", items: [], priority: 2, active: true },
  { id: "hub-problem-suporte-caindo", type: "problem", title: "Suporte caindo", slug: "suporte-caindo", categorySlug: "trabalho-e-produtividade", query: "suporte celular", items: [], priority: 3, active: true },
  { id: "hub-problem-carro-sujo", type: "problem", title: "Carro sujo", slug: "carro-sujo", categorySlug: "limpeza-higiene-e-estetica", query: "limpeza", items: [], priority: 4, active: true },
  { id: "hub-problem-mau-cheiro", type: "problem", title: "Mau cheiro", slug: "mau-cheiro", categorySlug: "limpeza-higiene-e-estetica", query: "odores", items: [], priority: 5, active: true },
  { id: "hub-problem-desconforto", type: "problem", title: "Desconforto ao dirigir", slug: "desconforto-ao-dirigir", categorySlug: "organizacao-conforto-e-saude", query: "conforto lombar", items: [], priority: 6, active: true },
  { id: "hub-problem-organizacao", type: "problem", title: "Falta de organizacao", slug: "falta-de-organizacao", categorySlug: "organizacao-conforto-e-saude", query: "organizador", items: [], priority: 7, active: true },
  { id: "hub-problem-chuva", type: "problem", title: "Trabalho na chuva", slug: "trabalho-na-chuva", categorySlug: "seguranca-clima-e-emergencia", query: "chuva", items: [], priority: 8, active: true },
  { id: "hub-problem-pneu", type: "problem", title: "Pneu sem pressao", slug: "pneu-sem-pressao", categorySlug: "manutencao-pecas-e-pneus", query: "compressor", items: [], priority: 9, active: true },
  { id: "hub-problem-bateria", type: "problem", title: "Bateria descarregada", slug: "bateria-descarregada", categorySlug: "seguranca-clima-e-emergencia", query: "bateria", items: [], priority: 10, active: true },
  { id: "hub-problem-pedidos", type: "problem", title: "Pedidos desorganizados", slug: "pedidos-desorganizados", categorySlug: "moto-vestimentas-e-delivery", query: "delivery", items: [], priority: 11, active: true },
  { id: "hub-problem-registro-transito", type: "problem", title: "Registrar o transito", slug: "registrar-o-transito", categorySlug: "tecnologia-e-eletronicos", query: "dashcam", items: [], priority: 12, active: true },
  { id: "hub-objective-economizar", type: "objective", title: "Economizar combustivel", slug: "economizar-combustivel", subtitle: "Calibragem, manutencao e controle de consumo.", categorySlug: "manutencao-pecas-e-pneus", items: [], priority: 1, active: true },
  { id: "hub-objective-reduzir-manutencao", type: "objective", title: "Reduzir manutencao", slug: "reduzir-manutencao", subtitle: "Revisao preventiva, OBD2, bateria e filtros.", categorySlug: "manutencao-pecas-e-pneus", items: [], priority: 2, active: true },
  { id: "hub-objective-avaliacoes", type: "objective", title: "Melhorar avaliacoes", slug: "melhorar-avaliacoes", subtitle: "Limpeza, conforto e atendimento ao passageiro.", categorySlug: "organizacao-conforto-e-saude", items: [], priority: 3, active: true },
  { id: "hub-objective-produtividade", type: "objective", title: "Ganhar produtividade", slug: "ganhar-produtividade", subtitle: "Energia, suportes, organizacao e delivery.", categorySlug: "trabalho-e-produtividade", items: [], priority: 4, active: true },
  { id: "hub-objective-viagem", type: "objective", title: "Preparar para viagem", slug: "preparar-para-viagem", subtitle: "Bagagem, emergencia, alimentacao e navegacao.", categorySlug: "acessorios-viagem-e-servicos", items: [], priority: 5, active: true },
  { id: "hub-objective-seguranca", type: "objective", title: "Trabalhar com seguranca", slug: "trabalhar-com-seguranca", subtitle: "Camera, visibilidade, pneus e sinalizacao.", categorySlug: "seguranca-clima-e-emergencia", items: [], priority: 6, active: true },
  { id: "hub-profession-app", type: "profession", title: "Motorista de aplicativo", slug: "motorista-de-aplicativo", items: ["Essenciais para comecar", "Celular e carregamento", "Atendimento", "Conforto", "Limpeza", "Kits completos"], priority: 1, active: true },
  { id: "hub-profession-taxista", type: "profession", title: "Taxista", slug: "taxista", items: ["Atendimento ao passageiro", "Organizacao", "Seguranca", "Conservacao", "Tecnologia"], priority: 2, active: true },
  { id: "hub-profession-motoboy", type: "profession", title: "Motoboy", slug: "motoboy", items: ["Chuva", "Baus e bags", "Suporte antivibracao", "Visibilidade", "Manutencao de corrente"], priority: 3, active: true },
  { id: "hub-profession-entregador-carro", type: "profession", title: "Entregador de carro", slug: "entregador-de-carro", items: ["Pedidos", "Bebidas", "Porta-malas", "Limpeza rapida", "Controle de custos"], priority: 4, active: true },
  { id: "hub-profession-ciclista", type: "profession", title: "Ciclista entregador", slug: "ciclista-entregador", items: ["Iluminacao", "Bolsas", "Hidratacao", "Seguranca", "Kit chuva"], priority: 5, active: true },
  { id: "hub-profession-motorista-profissional", type: "profession", title: "Motorista profissional", slug: "motorista-profissional", items: ["Alta quilometragem", "Conforto", "Emergencia", "Tecnologia", "Viagem"], priority: 6, active: true },
  { id: "hub-kit-app-iniciante", type: "kit", title: "Kit motorista de aplicativo iniciante", slug: "kit-motorista-de-aplicativo-iniciante", categorySlug: "kits-loja-do-korre", query: "motorista de aplicativo iniciante", items: [], priority: 1, active: true },
  { id: "hub-kit-cinco-estrelas", type: "kit", title: "Kit motorista cinco estrelas", slug: "kit-motorista-cinco-estrelas", categorySlug: "kits-loja-do-korre", query: "motorista cinco estrelas", items: [], priority: 2, active: true },
  { id: "hub-kit-motoboy-chuva", type: "kit", title: "Kit motoboy chuva", slug: "kit-motoboy-chuva", categorySlug: "kits-loja-do-korre", query: "motoboy chuva", items: [], priority: 3, active: true },
  { id: "hub-kit-celular-carregado", type: "kit", title: "Kit celular sempre carregado", slug: "kit-celular-sempre-carregado", categorySlug: "kits-loja-do-korre", query: "celular sempre carregado", items: [], priority: 4, active: true },
  { id: "hub-kit-limpeza", type: "kit", title: "Kit limpeza rapida", slug: "kit-limpeza-rapida", categorySlug: "kits-loja-do-korre", query: "limpeza rapida", items: [], priority: 5, active: true },
  { id: "hub-content-guias", type: "content", title: "Guias de compra", slug: "guias-de-compra", subtitle: "Como escolher suporte, carregador, dashcam, compressor e mochila termica.", items: [], priority: 1, active: true },
  { id: "hub-content-reviews", type: "content", title: "Reviews", slug: "reviews", subtitle: "Analise de uso, pontos positivos, limitacoes, compatibilidade e alternativas.", items: [], priority: 2, active: true },
  { id: "hub-content-comparativos", type: "content", title: "Comparativos", slug: "comparativos", subtitle: "Produto contra produto, barato contra premium, marcas, tecnologias e tamanhos.", items: [], priority: 3, active: true },
  { id: "hub-season-chuva", type: "seasonal", title: "Chuva, calor, frio, ferias e datas profissionais", slug: "clima-e-sazonalidade", subtitle: "Campanhas podem destacar capas, impermeabilizacao, hidratacao, ventilacao, viagem, presentes e kits por faixa de preco.", categorySlug: "seguranca-clima-e-emergencia", query: "chuva", items: [], priority: 1, active: true }
];
