import type { Category, Product } from "@korre/shared";

export const categories: Category[] = [
  {
    id: "cat-trabalho-produtividade",
    name: "Trabalho e produtividade",
    slug: "trabalho-e-produtividade",
    description: "Essenciais para operar apps, atender passageiros, entregar pedidos e organizar a jornada.",
    icon: "briefcase",
    subcategories: ["Suportes para celular", "Carregadores", "Cabos", "Power banks", "Atendimento ao passageiro", "Bags de entrega", "Mochilas termicas", "Gestao da jornada"],
    sortOrder: 1,
    active: true
  },
  {
    id: "cat-eletronicos",
    name: "Eletronicos",
    slug: "eletronicos",
    description: "Celulares, carregadores, power banks, cabos e acessorios para manter a operacao conectada.",
    icon: "smartphone",
    subcategories: ["Celulares", "Carregadores", "Power banks", "Cabos reforcados", "Coolers para celular", "Impressoras portateis"],
    sortOrder: 2,
    active: true
  },
  {
    id: "cat-tecnologia-veicular",
    name: "Tecnologia veicular",
    slug: "tecnologia-veicular",
    description: "Multimidia, cameras, sensores, diagnostico e energia para dirigir com mais controle.",
    icon: "cpu",
    subcategories: ["Multimidia", "Dashcams", "Cameras de re", "Sensores", "OBD2", "Energia", "GPS", "Conectividade"],
    sortOrder: 3,
    active: true
  },
  {
    id: "cat-autopecas",
    name: "Autopecas",
    slug: "autopecas",
    description: "Pecas de reposicao e itens de manutencao preventiva ou corretiva.",
    icon: "wrench",
    subcategories: ["Motor", "Filtros", "Freios", "Suspensao", "Direcao", "Correias", "Ignicao", "Arrefecimento", "Palhetas", "Eletrica", "Baterias"],
    sortOrder: 4,
    active: true
  },
  {
    id: "cat-pneus-rodas",
    name: "Pneus e rodas",
    slug: "pneus-e-rodas",
    description: "Pneus, rodas, calotas e reparos para carro, moto, bicicleta e utilitarios.",
    icon: "circle",
    subcategories: ["Pneus de passeio", "Pneus SUV", "Pneus utilitarios", "Pneus de moto", "Pneus de bicicleta", "Rodas", "Calotas", "Kit reparo", "Compressor", "Selante"],
    sortOrder: 5,
    active: true
  },
  {
    id: "cat-ferramentas",
    name: "Ferramentas",
    slug: "ferramentas",
    description: "Ferramentas para pequenos reparos, revisoes e emergencias operacionais.",
    icon: "tool",
    subcategories: ["Kits de ferramentas", "Chaves", "Alicates", "Torquimetros", "Lanternas", "Multimetros", "Organizadores"],
    sortOrder: 6,
    active: true
  },
  {
    id: "cat-manutencao",
    name: "Manutencao preventiva",
    slug: "manutencao",
    description: "Lubrificantes, aditivos, graxas, limpeza tecnica e manutencao preventiva.",
    icon: "settings",
    subcategories: ["Fluidos", "Filtros", "Ignicao", "Freios", "Pneus", "Bateria", "Visibilidade", "Moto", "Bicicleta"],
    sortOrder: 7,
    active: true
  },
  {
    id: "cat-manutencao-corretiva",
    name: "Manutencao corretiva",
    slug: "manutencao-corretiva",
    description: "Pecas e itens para corrigir falhas comuns com orientacao de compatibilidade.",
    icon: "wrench",
    subcategories: ["Motor", "Eletrica", "Freios", "Suspensao", "Direcao", "Transmissao", "Acabamento", "Moto", "Bicicleta"],
    sortOrder: 8,
    active: true
  },
  {
    id: "cat-limpeza-higienizacao",
    name: "Limpeza e higienizacao",
    slug: "limpeza-e-higienizacao",
    description: "Limpeza interna, externa, odores e protecao para manter o veiculo pronto para trabalhar.",
    icon: "sparkles",
    subcategories: ["Interna", "Externa", "Vidros", "Estofados", "Couro", "Painel", "Rodas", "Odores", "Lavagem a seco", "Limpeza rapida", "Kits profissionais", "Protecao"],
    sortOrder: 9,
    active: true
  },
  {
    id: "cat-estetica",
    name: "Estetica automotiva",
    slug: "estetica-automotiva",
    description: "Produtos para conservar, limpar e melhorar a aparencia do veiculo.",
    icon: "sparkles",
    subcategories: ["Lavagem", "Cera", "Polimento", "Cristalizacao", "Limpeza de bancos", "Limpeza de couro", "Aromatizantes", "Aspiradores"],
    sortOrder: 10,
    active: true
  },
  {
    id: "cat-organizacao",
    name: "Organizacao do veiculo",
    slug: "organizacao-do-veiculo",
    description: "Itens para manter documentos, objetos, bagagens e ferramentas no lugar.",
    icon: "archive",
    subcategories: ["Interior", "Porta-malas", "Banco traseiro", "Console", "Documentos", "Cabos", "Ferramentas", "Pedidos", "Alimentos", "Moto", "Bicicleta", "Viagem"],
    sortOrder: 11,
    active: true
  },
  {
    id: "cat-seguranca",
    name: "Seguranca",
    slug: "seguranca",
    description: "Itens para emergencias, prevencao de risco e seguranca em rota.",
    icon: "shield",
    subcategories: ["Visibilidade", "Registro por camera", "Monitoramento", "Pneus", "Iluminacao", "Chuva", "Emergencia", "Protecao para moto", "Protecao para bicicleta", "Passageiros", "Protecao do veiculo"],
    sortOrder: 12,
    active: true
  },
  {
    id: "cat-emergencia-imprevistos",
    name: "Emergencia",
    slug: "emergencia",
    description: "Kits e equipamentos para panes, pneus, bateria, chuva, sinalizacao e primeiros cuidados.",
    icon: "alert-triangle",
    subcategories: ["Bateria", "Pneus", "Iluminacao", "Energia", "Sinalizacao", "Chuva", "Primeiros cuidados", "Organizacao do kit", "Documentacao", "Ferramentas"],
    sortOrder: 13,
    active: true
  },
  {
    id: "cat-clima-protecao",
    name: "Clima e protecao",
    slug: "clima-e-protecao",
    description: "Produtos para trabalhar com chuva, calor, frio, poeira e lama.",
    icon: "cloud-rain",
    subcategories: ["Chuva", "Calor", "Frio", "Poeira", "Lama", "Impermeabilizacao", "Protecao solar", "Ventilacao"],
    sortOrder: 14,
    active: true
  },
  {
    id: "cat-viagens-rodoviario",
    name: "Viagens e uso rodoviario",
    slug: "viagens-e-uso-rodoviario",
    description: "Bagagem, energia, conforto, emergencia e alimentacao para trajetos longos.",
    icon: "map",
    subcategories: ["Bagagem", "Alimentacao", "Conforto", "Energia", "Navegacao", "Emergencia", "Criancas", "Animais", "Estrada"],
    sortOrder: 15,
    active: true
  },
  {
    id: "cat-vestimentas",
    name: "Vestimentas",
    slug: "vestimentas",
    description: "Capas de chuva, luvas, jaquetas, refletivos e protecoes para a rotina na rua.",
    icon: "shirt",
    subcategories: ["Capas de chuva", "Luvas", "Jaquetas", "Refletivos"],
    sortOrder: 16,
    active: true
  },
  {
    id: "cat-capacetes",
    name: "Capacetes",
    slug: "capacetes",
    description: "Capacetes, viseiras e comunicacao para motociclistas e entregadores.",
    icon: "helmet",
    subcategories: ["Aberto", "Fechado", "Articulado", "Off-road", "Viseiras", "Intercomunicadores"],
    sortOrder: 17,
    active: true
  },
  {
    id: "cat-motocicletas",
    name: "Motocicletas",
    slug: "motocicletas",
    description: "Celular, chuva, baus, bags, seguranca, conforto e manutencao para moto.",
    icon: "bike",
    subcategories: ["Equipamentos do motociclista", "Celular e navegacao", "Chuva", "Baus e bolsas", "Entregas", "Seguranca", "Conforto", "Manutencao", "Ferramentas"],
    sortOrder: 18,
    active: true
  },
  {
    id: "cat-conforto",
    name: "Conforto",
    slug: "conforto",
    description: "Produtos para reduzir desgaste fisico em jornadas longas.",
    icon: "armchair",
    subcategories: ["Assento e postura", "Temperatura", "Hidratacao", "Alimentacao", "Protecao solar", "Vestuario", "Conforto para passageiro", "Conforto para moto", "Conforto para bicicleta", "Viagem longa"],
    sortOrder: 19,
    active: true
  },
  {
    id: "cat-alimentacao",
    name: "Alimentacao",
    slug: "alimentacao",
    description: "Itens para agua, cafe, marmita e alimentacao durante o trabalho.",
    icon: "cup",
    subcategories: ["Garrafas termicas", "Copos termicos", "Caixas termicas", "Marmitas", "Bolsas termicas", "Cafeteiras automotivas"],
    sortOrder: 20,
    active: true
  },
  {
    id: "cat-saude-higiene",
    name: "Saude e higiene",
    slug: "saude-e-higiene",
    description: "Cuidados pessoais, primeiros socorros e higiene para a rotina na rua.",
    icon: "heart",
    subcategories: ["Primeiros socorros", "Protetor solar", "Repelentes", "Mascaras", "Alcool em gel", "Lencos", "Papel toalha", "Escova dental", "Desodorantes"],
    sortOrder: 21,
    active: true
  },
  {
    id: "cat-delivery",
    name: "Delivery",
    slug: "delivery",
    description: "Bags, baus, redes e acessorios para motoboys e entregadores.",
    icon: "package",
    subcategories: ["Mochilas", "Baus", "Bagageiros", "Elasticos", "Redes", "Capas termicas", "Bags impermeaveis"],
    sortOrder: 22,
    active: true
  },
  {
    id: "cat-bicicletas",
    name: "Bicicletas",
    slug: "bicicletas",
    description: "Equipamentos para ciclistas profissionais e entregadores de bike.",
    icon: "bike",
    subcategories: ["Iluminacao", "Seguranca", "Celular", "Bolsas e transporte", "Entregas", "Hidratacao", "Conforto", "Manutencao", "Ferramentas"],
    sortOrder: 23,
    active: true
  },
  {
    id: "cat-equipamentos",
    name: "Equipamentos",
    slug: "equipamentos",
    description: "Suportes, bags, mochilas, organizadores e itens de apoio para trabalho.",
    icon: "briefcase",
    subcategories: ["Suportes para celular", "Bags e mochilas", "Organizadores", "Acessorios de apoio"],
    sortOrder: 24,
    active: true
  },
  {
    id: "cat-pecas",
    name: "Pecas",
    slug: "pecas",
    description: "Itens de manutencao simples e pecas de reposicao para carro, moto, bike e scooter.",
    icon: "wrench",
    subcategories: ["Pecas de revisao", "Freios", "Iluminacao", "Kits de reparo"],
    sortOrder: 25,
    active: false
  },
  {
    id: "cat-servicos-protecao",
    name: "Servicos e protecao",
    slug: "servicos-e-protecao",
    description: "Servicos recorrentes e protecao para quem depende do veiculo.",
    icon: "badge",
    subcategories: ["Seguro automotivo", "Rastreadores", "Assistencia 24h", "Protecao veicular"],
    sortOrder: 26,
    active: true
  },
  {
    id: "cat-acessorios-automotivos",
    name: "Acessorios para carro",
    slug: "acessorios-para-carro",
    description: "Tapetes, peliculas, capas, adesivos e itens internos do veiculo.",
    icon: "car",
    subcategories: ["Interior", "Exterior", "Tapetes", "Capas", "Peliculas", "Porta-malas", "Console", "Bancos", "Volante", "Acabamento"],
    sortOrder: 27,
    active: true
  },
  {
    id: "cat-transporte-passageiros",
    name: "Passageiros e familia",
    slug: "passageiros-e-familia",
    description: "Itens para passageiros, criancas, animais, organizacao e conforto no banco traseiro.",
    icon: "users",
    subcategories: ["Passageiros", "Criancas", "Animais", "Porta-copos", "Protetores de banco", "Lixeiras", "Organizadores", "Conforto"],
    sortOrder: 28,
    active: true
  },
  {
    id: "cat-documentacao-gestao",
    name: "Documentacao e gestao",
    slug: "documentacao-e-gestao",
    description: "Apoio para controle de jornada, documentos, custos, quilometragem e rotina profissional.",
    icon: "clipboard-list",
    subcategories: ["Documentos", "Controle de custos", "Quilometragem", "Planejamento", "Recibos", "Pastas", "Etiquetas", "Organizacao digital"],
    sortOrder: 29,
    active: true
  },
  {
    id: "cat-iluminacao",
    name: "Iluminacao",
    slug: "iluminacao",
    description: "Farois, lanternas, LEDs e sinalizacao para dirigir melhor e ser visto.",
    icon: "lightbulb",
    subcategories: ["LED", "Farois", "Lanternas", "Milhas", "Lampadas internas"],
    sortOrder: 30,
    active: true
  },
  {
    id: "cat-kits-korre",
    name: "Kits Loja do Korre",
    slug: "kits-loja-do-korre",
    description: "Combos prontos por profissao, clima, jornada e objetivo.",
    icon: "boxes",
    subcategories: ["Por profissao", "Por problema", "Por orcamento", "Por jornada", "Economicos", "Custo-beneficio", "Premium", "Kit chuva", "Kit noite", "Kit emergencia", "Kit delivery"],
    sortOrder: 31,
    active: true
  }
];

export const products: Product[] = [
  {
    id: "prod-suporte-celular",
    categoryId: "cat-equipamentos",
    categorySlug: "equipamentos",
    name: "Suporte veicular com trava reforcada",
    slug: "suporte-veicular-trava-reforcada",
    shortDescription: "Boa opcao para quem usa GPS por horas e precisa reduzir vibracao.",
    recommendationReason: "Mantem o aparelho firme e facilita visualizar rotas sem improviso no painel.",
    vehicleType: "car",
    audience: "driver",
    imageUrl: "https://images.unsplash.com/photo-1617788138017-80ad40651399?auto=format&fit=crop&w=900&q=80",
    referencePriceCents: 6990,
    currency: "BRL",
    status: "active",
    featured: true,
    tags: ["suportes para celular", "gps", "carro", "rotina"],
    bestFor: "Motoristas de app que passam o dia alternando entre mapas, chamadas e corridas.",
    avoidWhen: "O painel do veiculo nao tem area firme para ventosa ou base adesiva.",
    offer: {
      id: "offer-suporte-celular",
      provider: "mercado_livre",
      affiliateUrl: "https://www.mercadolivre.com.br/",
      active: true,
      referencePriceCents: 6990,
      updatedAt: new Date().toISOString()
    }
  },
  {
    id: "prod-cabo-reforcado",
    categoryId: "cat-eletronicos",
    categorySlug: "eletronicos",
    name: "Cabo USB-C reforcado para carga rapida",
    slug: "cabo-usb-c-reforcado-carga-rapida",
    shortDescription: "Cabo extra para deixar no carro, moto ou mochila sem depender do principal.",
    recommendationReason: "Evita parar a operacao por bateria baixa e aguenta melhor dobra e manuseio frequente.",
    vehicleType: "both",
    audience: "general",
    imageUrl: "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=900&q=80",
    referencePriceCents: 3990,
    currency: "BRL",
    status: "active",
    featured: true,
    tags: ["carregadores", "energia", "usb-c", "carga"],
    bestFor: "Quem alterna entre veiculo, power bank e tomada durante o dia.",
    avoidWhen: "Seu celular usa outro padrao de conector ou exige cabo certificado especifico.",
    offer: {
      id: "offer-cabo-reforcado",
      provider: "mercado_livre",
      affiliateUrl: "https://www.mercadolivre.com.br/",
      active: true,
      referencePriceCents: 3990,
      updatedAt: new Date().toISOString()
    }
  },
  {
    id: "prod-capa-chuva",
    categoryId: "cat-vestimentas",
    categorySlug: "vestimentas",
    name: "Capa de chuva para entrega",
    slug: "capa-de-chuva-para-entrega",
    shortDescription: "Camada de protecao para motoboy que nao pode parar quando o tempo vira.",
    recommendationReason: "Ajuda a manter roupa e equipamentos secos em jornadas com chuva intermitente.",
    vehicleType: "motorcycle",
    audience: "motoboy",
    imageUrl: "https://images.unsplash.com/photo-1520607162513-77705c0f0d4a?auto=format&fit=crop&w=900&q=80",
    referencePriceCents: 11990,
    currency: "BRL",
    status: "active",
    featured: false,
    tags: ["capa de chuva", "moto", "chuva", "entrega"],
    bestFor: "Entregadores que rodam mesmo em periodos de chuva e precisam secar rapido.",
    avoidWhen: "Voce precisa de EPI com certificacao especifica exigida pela empresa contratante.",
    offer: {
      id: "offer-capa-chuva",
      provider: "mercado_livre",
      affiliateUrl: "https://www.mercadolivre.com.br/",
      active: true,
      referencePriceCents: 11990,
      updatedAt: new Date().toISOString()
    }
  }
  ,
  {
    id: "prod-celular-reserva",
    categoryId: "cat-eletronicos",
    categorySlug: "eletronicos",
    name: "Celular reserva para aplicativos",
    slug: "celular-reserva-para-aplicativos",
    shortDescription: "Aparelho de apoio para quem precisa manter corridas, mapas e comunicacao sempre disponiveis.",
    recommendationReason: "Ajuda a separar uso pessoal da operacao e reduz risco de ficar sem ferramenta de trabalho.",
    vehicleType: "both",
    audience: "general",
    imageUrl: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=900&q=80",
    referencePriceCents: 79990,
    currency: "BRL",
    status: "active",
    featured: false,
    tags: ["celulares", "aplicativos", "gps"],
    bestFor: "Motoristas e entregadores que dependem do celular durante toda a jornada.",
    avoidWhen: "Voce precisa de camera premium ou alto desempenho para jogos.",
    offer: {
      id: "offer-celular-reserva",
      provider: "mercado_livre",
      affiliateUrl: "https://www.mercadolivre.com.br/",
      active: true,
      referencePriceCents: 79990,
      updatedAt: new Date().toISOString()
    }
  },
  {
    id: "prod-kit-pastilha-freio",
    categoryId: "cat-autopecas",
    categorySlug: "autopecas",
    name: "Kit de pastilhas de freio para revisao",
    slug: "kit-pastilhas-freio-revisao",
    shortDescription: "Item de manutencao preventiva para revisar antes de jornadas longas.",
    recommendationReason: "Freio em dia reduz risco operacional e evita parar de trabalhar por desgaste ignorado.",
    vehicleType: "motorcycle",
    audience: "motoboy",
    imageUrl: "https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=900&q=80",
    referencePriceCents: 8990,
    currency: "BRL",
    status: "active",
    featured: false,
    tags: ["pecas", "freio", "manutencao", "moto"],
    bestFor: "Motoboys que fazem revisao periodica e conhecem a compatibilidade da moto.",
    avoidWhen: "Voce nao tem certeza do modelo correto para seu veiculo.",
    offer: {
      id: "offer-kit-pastilha-freio",
      provider: "mercado_livre",
      affiliateUrl: "https://www.mercadolivre.com.br/",
      active: true,
      referencePriceCents: 8990,
      updatedAt: new Date().toISOString()
    }
  },
  {
    id: "prod-carregador-veicular-duplo",
    categoryId: "cat-trabalho-produtividade",
    categorySlug: "trabalho-e-produtividade",
    name: "Carregador veicular duplo carga rapida",
    slug: "carregador-veicular-duplo-carga-rapida",
    shortDescription: "Energia para celular do motorista e passageiro sem improvisar adaptadores.",
    recommendationReason: "Resolve o ponto mais critico da jornada: manter apps, GPS e comunicacao ligados.",
    vehicleType: "car",
    audience: "driver",
    imageUrl: "https://images.unsplash.com/photo-1603791440384-56cd371ee9a7?auto=format&fit=crop&w=900&q=80",
    referencePriceCents: 5990,
    currency: "BRL",
    status: "active",
    featured: true,
    tags: ["carregador", "celular descarregando", "atendimento ao passageiro", "energia"],
    bestFor: "Motoristas de aplicativo que precisam carregar dois aparelhos ou atender passageiro.",
    avoidWhen: "Seu veiculo ja possui USB-C nativo com potencia suficiente.",
    offer: {
      id: "offer-carregador-veicular-duplo",
      provider: "mercado_livre",
      affiliateUrl: "https://www.mercadolivre.com.br/",
      active: true,
      referencePriceCents: 5990,
      updatedAt: new Date().toISOString()
    }
  },
  {
    id: "prod-dashcam-dupla",
    categoryId: "cat-tecnologia-veicular",
    categorySlug: "tecnologia-veicular",
    name: "Dashcam dupla para registro de rota",
    slug: "dashcam-dupla-registro-rota",
    shortDescription: "Camera frontal e interna para registrar acontecimentos durante corridas e viagens.",
    recommendationReason: "Aumenta a confianca em situacoes de contestacao, incidentes e trabalho noturno.",
    vehicleType: "car",
    audience: "driver",
    imageUrl: "https://images.unsplash.com/photo-1617824040896-4b771231a33f?auto=format&fit=crop&w=900&q=80",
    referencePriceCents: 28990,
    currency: "BRL",
    status: "active",
    featured: true,
    tags: ["dashcam", "camera", "registro do transito", "seguranca"],
    bestFor: "Motoristas que transportam passageiros ou rodam em horarios de maior risco.",
    avoidWhen: "Voce nao quer lidar com instalacao, fio aparente ou cartao de memoria.",
    offer: {
      id: "offer-dashcam-dupla",
      provider: "mercado_livre",
      affiliateUrl: "https://www.mercadolivre.com.br/",
      active: true,
      referencePriceCents: 28990,
      updatedAt: new Date().toISOString()
    }
  },
  {
    id: "prod-kit-limpeza-rapida",
    categoryId: "cat-limpeza-higienizacao",
    categorySlug: "limpeza-e-higienizacao",
    name: "Kit limpeza rapida para carro de trabalho",
    slug: "kit-limpeza-rapida-carro-trabalho",
    shortDescription: "Panos, limpador interno e neutralizador para manter o carro apresentavel entre corridas.",
    recommendationReason: "Ajuda a recuperar o padrao de atendimento depois de sujeira, chuva ou passageiro descuidado.",
    vehicleType: "car",
    audience: "driver",
    imageUrl: "https://images.unsplash.com/photo-1607860108855-64acf2078ed9?auto=format&fit=crop&w=900&q=80",
    referencePriceCents: 8490,
    currency: "BRL",
    status: "active",
    featured: true,
    tags: ["limpeza", "limpeza rapida", "carro sujo", "odores"],
    bestFor: "Motoristas que precisam manter boa avaliacao sem parar muito tempo.",
    avoidWhen: "O veiculo precisa de limpeza profunda ou higienizacao profissional.",
    offer: {
      id: "offer-kit-limpeza-rapida",
      provider: "mercado_livre",
      affiliateUrl: "https://www.mercadolivre.com.br/",
      active: true,
      referencePriceCents: 8490,
      updatedAt: new Date().toISOString()
    }
  },
  {
    id: "prod-apoio-lombar-motorista",
    categoryId: "cat-conforto",
    categorySlug: "conforto",
    name: "Apoio lombar para longas jornadas",
    slug: "apoio-lombar-longas-jornadas",
    shortDescription: "Almofada de suporte para reduzir desconforto em turnos prolongados.",
    recommendationReason: "Melhora postura e ajuda quem sente dor depois de muitas horas dirigindo.",
    vehicleType: "car",
    audience: "driver",
    imageUrl: "https://images.unsplash.com/photo-1550355291-bbee04a92027?auto=format&fit=crop&w=900&q=80",
    referencePriceCents: 7990,
    currency: "BRL",
    status: "active",
    featured: false,
    tags: ["conforto lombar", "desconforto", "ergonomia", "jornada longa"],
    bestFor: "Motoristas que passam horas sentados e querem uma melhoria simples de ergonomia.",
    avoidWhen: "O banco ja tem ajuste lombar eficiente ou ha dor que exige avaliacao profissional.",
    offer: {
      id: "offer-apoio-lombar-motorista",
      provider: "mercado_livre",
      affiliateUrl: "https://www.mercadolivre.com.br/",
      active: true,
      referencePriceCents: 7990,
      updatedAt: new Date().toISOString()
    }
  },
  {
    id: "prod-compressor-portatil",
    categoryId: "cat-pneus-rodas",
    categorySlug: "pneus-e-rodas",
    name: "Compressor portatil para pneus",
    slug: "compressor-portatil-pneus",
    shortDescription: "Calibragem e emergencia para carro, moto e bicicleta.",
    recommendationReason: "Reduz parada inesperada por pneu baixo e ajuda a economizar combustivel com calibragem correta.",
    vehicleType: "both",
    audience: "general",
    imageUrl: "https://images.unsplash.com/photo-1487754180451-c456f719a1fc?auto=format&fit=crop&w=900&q=80",
    referencePriceCents: 16990,
    currency: "BRL",
    status: "active",
    featured: true,
    tags: ["compressor", "pneu sem pressao", "calibragem", "economizar combustivel"],
    bestFor: "Quem roda muito e quer manter pressao correta sem depender sempre de posto.",
    avoidWhen: "Voce precisa inflar pneus grandes acima da capacidade do aparelho.",
    offer: {
      id: "offer-compressor-portatil",
      provider: "mercado_livre",
      affiliateUrl: "https://www.mercadolivre.com.br/",
      active: true,
      referencePriceCents: 16990,
      updatedAt: new Date().toISOString()
    }
  },
  {
    id: "prod-auxiliar-partida",
    categoryId: "cat-emergencia-imprevistos",
    categorySlug: "emergencia",
    name: "Auxiliar de partida compacto",
    slug: "auxiliar-partida-compacto",
    shortDescription: "Fonte de emergencia para bateria descarregada em rotina profissional.",
    recommendationReason: "Evita perder horas de trabalho esperando ajuda quando a bateria falha.",
    vehicleType: "car",
    audience: "driver",
    imageUrl: "https://images.unsplash.com/photo-1530046339160-ce3e530c7d2f?auto=format&fit=crop&w=900&q=80",
    referencePriceCents: 24990,
    currency: "BRL",
    status: "active",
    featured: false,
    tags: ["bateria", "bateria descarregada", "emergencia", "energia"],
    bestFor: "Motoristas que trabalham de madrugada, viajam ou rodam alta quilometragem.",
    avoidWhen: "A bateria apresenta defeito recorrente que precisa de diagnostico profissional.",
    offer: {
      id: "offer-auxiliar-partida",
      provider: "mercado_livre",
      affiliateUrl: "https://www.mercadolivre.com.br/",
      active: true,
      referencePriceCents: 24990,
      updatedAt: new Date().toISOString()
    }
  },
  {
    id: "prod-mochila-termica-delivery",
    categoryId: "cat-delivery",
    categorySlug: "delivery",
    name: "Mochila termica para delivery",
    slug: "mochila-termica-delivery",
    shortDescription: "Transporte de pedidos com melhor organizacao e conservacao de temperatura.",
    recommendationReason: "Ajuda a reduzir reclamacao por pedido amassado, frio ou mal acomodado.",
    vehicleType: "motorcycle",
    audience: "motoboy",
    imageUrl: "https://images.unsplash.com/photo-1526367790999-0150786686a2?auto=format&fit=crop&w=900&q=80",
    referencePriceCents: 13990,
    currency: "BRL",
    status: "active",
    featured: false,
    tags: ["delivery", "pedidos desorganizados", "mochila termica", "motoboy"],
    bestFor: "Motoboys e ciclistas entregadores que fazem rota com pedidos variados.",
    avoidWhen: "Voce precisa transportar volumes muito grandes ou caixas rigidas.",
    offer: {
      id: "offer-mochila-termica-delivery",
      provider: "mercado_livre",
      affiliateUrl: "https://www.mercadolivre.com.br/",
      active: true,
      referencePriceCents: 13990,
      updatedAt: new Date().toISOString()
    }
  },
  {
    id: "prod-kit-chuva-profissional",
    categoryId: "cat-kits-korre",
    categorySlug: "kits-loja-do-korre",
    name: "Kit chuva para rotina profissional",
    slug: "kit-chuva-rotina-profissional",
    shortDescription: "Selecao inicial para trabalhar quando o tempo vira.",
    recommendationReason: "Combina protecao pessoal, impermeabilizacao e visibilidade em um caminho de compra.",
    vehicleType: "both",
    audience: "general",
    imageUrl: "https://images.unsplash.com/photo-1493314894560-5c412a56c17c?auto=format&fit=crop&w=900&q=80",
    referencePriceCents: 19990,
    currency: "BRL",
    status: "active",
    featured: false,
    tags: ["kit chuva", "chuva", "trabalho noturno", "emergencia"],
    bestFor: "Motoristas e entregadores que querem montar uma base antes do periodo de chuvas.",
    avoidWhen: "Voce precisa de item homologado por regra especifica do contratante.",
    offer: {
      id: "offer-kit-chuva-profissional",
      provider: "mercado_livre",
      affiliateUrl: "https://www.mercadolivre.com.br/",
      active: true,
      referencePriceCents: 19990,
      updatedAt: new Date().toISOString()
    }
  }
];
